// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIF54KGYtQN3WIWTNXUGMWvyFFf8srfpE',
    appId: '1:863689132828:web:7c0a447c4c0285f11088d9',
    messagingSenderId: '863689132828',
    projectId: 'grad-implementation-ver-1',
    authDomain: 'grad-implementation-ver-1.firebaseapp.com',
    databaseURL: 'https://grad-implementation-ver-1-default-rtdb.firebaseio.com',
    storageBucket: 'grad-implementation-ver-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASkoUxoa3DJYNkbnH1BrNYiATadjq9Ebo',
    appId: '1:863689132828:android:859087d9719075151088d9',
    messagingSenderId: '863689132828',
    projectId: 'grad-implementation-ver-1',
    databaseURL: 'https://grad-implementation-ver-1-default-rtdb.firebaseio.com',
    storageBucket: 'grad-implementation-ver-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtMHcbVR2h3B4PEIuqQXyCNIQtiYKbrRw',
    appId: '1:863689132828:ios:a66c03561319ba7f1088d9',
    messagingSenderId: '863689132828',
    projectId: 'grad-implementation-ver-1',
    databaseURL: 'https://grad-implementation-ver-1-default-rtdb.firebaseio.com',
    storageBucket: 'grad-implementation-ver-1.firebasestorage.app',
    iosBundleId: 'com.example.gradImp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtMHcbVR2h3B4PEIuqQXyCNIQtiYKbrRw',
    appId: '1:863689132828:ios:a66c03561319ba7f1088d9',
    messagingSenderId: '863689132828',
    projectId: 'grad-implementation-ver-1',
    databaseURL: 'https://grad-implementation-ver-1-default-rtdb.firebaseio.com',
    storageBucket: 'grad-implementation-ver-1.firebasestorage.app',
    iosBundleId: 'com.example.gradImp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIF54KGYtQN3WIWTNXUGMWvyFFf8srfpE',
    appId: '1:863689132828:web:80bf3a1827adb0821088d9',
    messagingSenderId: '863689132828',
    projectId: 'grad-implementation-ver-1',
    authDomain: 'grad-implementation-ver-1.firebaseapp.com',
    databaseURL: 'https://grad-implementation-ver-1-default-rtdb.firebaseio.com',
    storageBucket: 'grad-implementation-ver-1.firebasestorage.app',
  );
}
